*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/X7R(-55to125[deg])/1.00e-01[uF]/10[V]
* Murata P/N :GRM033Z71A104KE14
* Property : C = 1.00e-01[uF]
* Data Generated on Jun 10, 2025
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM033Z71A104KE14 Port1 Port2
C01 Port1 N01 7.79e-08
R01 Port1 N01 5.00e+08
L02 N01 N02 1.58e-10
R03 N02 N03 2.90e-02
C04 N03 N04 3.39e-06
R04 N03 N04 1.17e+03
C05 N04 N05 4.20e-06
R05 N04 N05 1.38e+02
C06 N05 N06 4.33e-06
R06 N05 N06 1.95e+01
C07 N06 N07 3.49e-06
R07 N06 N07 4.07e+00
C08 N07 N08 3.04e-06
R08 N07 N08 6.10e-01
C09 N08 N09 2.05e-06
R09 N08 N09 1.24e-01
C10 N09 N10 1.11e-06
R10 N09 N10 2.21e-02
L11 N10 N11 1.73e-11
R11 N10 N11 3.77e-01
L12 N11 N12 4.44e-11
R12 N11 N12 1.54e-01
C13 N12 N13 1.99e-08
L13 N12 N13 4.78e-11
R13 N12 N13 2.86e-02
C14 N13 Port2 8.02e-10
L14 N13 Port2 8.39e-13
R14 N13 Port2 1.03e-01
.ENDS GRM033Z71A104KE14
