*----------------------------------------------------------------------
* SPICE Model generated by Murata Manufacturing Co., Ltd.
* Copyright(C) Murata Manufacturing Co., Ltd.
* Description :0603M(0201)/X5R(-55to85[deg])/1.00e+00[uF]/10[V]
* Murata P/N :GRM033R61A105ME44
* Property : C = 1.00e+00[uF]
* Data Generated on Jun 10, 2025
*----------------------------------------------------------------------
* Applicable Conditions:
*   Frequency Range = 100[Hz]-6[GHz]
*   Temperature = 25 degC
*   DC Bias Voltage = 0V
*   Small Signal Operation
*----------------------------------------------------------------------
.SUBCKT GRM033R61A105ME44 Port1 Port2
C01 Port1 N01 7.11e-07
R01 Port1 N01 5.00e+07
L02 N01 N02 1.39e-10
R03 N02 N03 7.27e-03
C04 N03 N04 5.22e-05
R04 N03 N04 3.71e+01
C05 N04 N05 6.24e-05
R05 N04 N05 7.61e+00
C06 N05 N06 5.62e-05
R06 N05 N06 1.62e+00
C07 N06 N07 5.19e-05
R07 N06 N07 3.14e-01
C08 N07 N08 4.65e-05
R08 N07 N08 5.16e-02
C09 N08 N09 2.64e-05
R09 N08 N09 1.23e-02
L10 N09 N10 5.75e-12
R10 N09 N10 1.45e-01
L11 N10 N11 1.33e-11
R11 N10 N11 7.78e-02
L12 N11 N12 2.03e-11
R12 N11 N12 3.08e-02
L13 N12 N13 1.00e-10
R13 N12 N13 2.41e-02
C14 N13 N14 3.08e-06
L14 N13 N14 1.65e-11
R14 N13 N14 3.55e-03
C15 N14 Port2 2.25e-06
L15 N14 Port2 1.20e-11
R15 N14 Port2 3.51e-03
.ENDS GRM033R61A105ME44
