[workspace]
pcb-version = "0.4"
vendor = ["code.diode.computer/diode/registry/**"]

[board]
name = "quad_rx_pre_amp"
path = "quad_rx_pre_amp.zen"
description = "Replace with concise board description."

[access]
allow = ["*"]