## Sonar v1 - Cmod A7-35T constraints (T-011 baseline for T-020)
## GENERATED by scripts/gen_digital_sheet.py - edit the generator or pinmap, not this file.
##
## PROVENANCE: DIP positions, PACKAGE_PINs and IO names VERIFIED 2026-08-26 against
## the live Digilent Cmod-A7-Master.xdc (orchestrator fetch) + reference manual sec. 8.
## The 2026-08-25 offline transcription had all net<->pkg pairings right but sat rows
## 15-44 on wrong DIP positions (pio15/16 = XADC analog, pio24 = VU, pio25 = GND; no 3V3
## pin exists). Fixed by re-map N->N (1-14), N->N+2 (15-21), N->N+4 (22-44); pkg pins
## unchanged. Reproducible check: python3 scripts/check_pinmap_vs_xdc.py (44/44 assert).
## URL: https://github.com/Digilent/digilent-xdc/blob/master/Cmod-A7-Master.xdc
##
## VCCO: all user banks (14/15/16/34/35) are fixed at 3.3V on the Cmod A7 -> LVCMOS33.

## 12 MHz on-module oscillator
set_property -dict { PACKAGE_PIN L17  IOSTANDARD LVCMOS33 } [get_ports { sysclk }]
create_clock -add -name sys_clk_pin -period 83.333 -waveform {0 41.667} [get_ports { sysclk }]

## On-module LEDs / buttons (debug)
set_property -dict { PACKAGE_PIN A17  IOSTANDARD LVCMOS33 } [get_ports { led[0] }]
set_property -dict { PACKAGE_PIN C16  IOSTANDARD LVCMOS33 } [get_ports { led[1] }]
set_property -dict { PACKAGE_PIN B17  IOSTANDARD LVCMOS33 } [get_ports { led0_b }]
set_property -dict { PACKAGE_PIN B16  IOSTANDARD LVCMOS33 } [get_ports { led0_g }]
set_property -dict { PACKAGE_PIN C17  IOSTANDARD LVCMOS33 } [get_ports { led0_r }]
set_property -dict { PACKAGE_PIN A18  IOSTANDARD LVCMOS33 } [get_ports { btn[0] }]
set_property -dict { PACKAGE_PIN B18  IOSTANDARD LVCMOS33 } [get_ports { btn[1] }]

## PDM microphone interface (T-008 baseline: 12 data lines, paired mics, returned clock)
set_property -dict { PACKAGE_PIN J3   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[0] }]
set_property -dict { PACKAGE_PIN J1   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[1] }]
set_property -dict { PACKAGE_PIN K2   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[2] }]
set_property -dict { PACKAGE_PIN L1   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[3] }]
set_property -dict { PACKAGE_PIN L2   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[4] }]
set_property -dict { PACKAGE_PIN M1   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[5] }]
set_property -dict { PACKAGE_PIN N3   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[6] }]
set_property -dict { PACKAGE_PIN P3   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[7] }]
set_property -dict { PACKAGE_PIN M2   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[8] }]
set_property -dict { PACKAGE_PIN N1   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[9] }]
set_property -dict { PACKAGE_PIN N2   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[10] }]
set_property -dict { PACKAGE_PIN P1   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[11] }]
set_property -dict { PACKAGE_PIN A14  IOSTANDARD LVCMOS33 } [get_ports { pdm_clk_src }]
set_property -dict { PACKAGE_PIN A15  IOSTANDARD LVCMOS33 } [get_ports { pdm_clk_en }]
## Returned clock from CDCLVC1112 Y11 - MUST land on a clock-capable pin (pio40, MRCC_34).
## IDDR sampling must use this returned clock, not a copy of the source net (capture contract).
set_property -dict { PACKAGE_PIN W4   IOSTANDARD LVCMOS33 } [get_ports { pdm_clk_fb }]
create_clock -add -name pdm_clk_fb_pin -period 325.521 -waveform {0 162.760} [get_ports { pdm_clk_fb }]  # 3.072 MHz v1 (parameterize; 208.333 ns for the 4.8 MHz ICS alternate)

## FT232H synchronous FIFO (FT245 sync mode, 60 MHz CLKOUT)
set_property -dict { PACKAGE_PIN R3   IOSTANDARD LVCMOS33 } [get_ports { ft_d[0] }]
set_property -dict { PACKAGE_PIN T3   IOSTANDARD LVCMOS33 } [get_ports { ft_d[1] }]
set_property -dict { PACKAGE_PIN R2   IOSTANDARD LVCMOS33 } [get_ports { ft_d[2] }]
set_property -dict { PACKAGE_PIN T1   IOSTANDARD LVCMOS33 } [get_ports { ft_d[3] }]
set_property -dict { PACKAGE_PIN T2   IOSTANDARD LVCMOS33 } [get_ports { ft_d[4] }]
set_property -dict { PACKAGE_PIN U1   IOSTANDARD LVCMOS33 } [get_ports { ft_d[5] }]
set_property -dict { PACKAGE_PIN W2   IOSTANDARD LVCMOS33 } [get_ports { ft_d[6] }]
set_property -dict { PACKAGE_PIN V2   IOSTANDARD LVCMOS33 } [get_ports { ft_d[7] }]
set_property -dict { PACKAGE_PIN W3   IOSTANDARD LVCMOS33 } [get_ports { ft_rxf_n }]
set_property -dict { PACKAGE_PIN V3   IOSTANDARD LVCMOS33 } [get_ports { ft_txe_n }]
set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports { ft_rd_n }]
set_property -dict { PACKAGE_PIN V4   IOSTANDARD LVCMOS33 } [get_ports { ft_wr_n }]
set_property -dict { PACKAGE_PIN U4   IOSTANDARD LVCMOS33 } [get_ports { ft_oe_n }]
set_property -dict { PACKAGE_PIN U8   IOSTANDARD LVCMOS33 } [get_ports { ft_clkout }]
create_clock -add -name ft_clkout_pin -period 16.667 -waveform {0 8.333} [get_ports { ft_clkout }]  # 60 MHz

## DNP RMII Ethernet provision (LAN8720A + 50 MHz osc; not populated on v1)
## Uncomment when the DNP block is populated.
#set_property -dict { PACKAGE_PIN V5   IOSTANDARD LVCMOS33 } [get_ports { eth_txd[0] }]
#set_property -dict { PACKAGE_PIN U5   IOSTANDARD LVCMOS33 } [get_ports { eth_txd[1] }]
#set_property -dict { PACKAGE_PIN U2   IOSTANDARD LVCMOS33 } [get_ports { eth_tx_en }]
#set_property -dict { PACKAGE_PIN W6   IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[0] }]
#set_property -dict { PACKAGE_PIN U3   IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[1] }]
#set_property -dict { PACKAGE_PIN U7   IOSTANDARD LVCMOS33 } [get_ports { eth_crs_dv }]
#set_property -dict { PACKAGE_PIN W7   IOSTANDARD LVCMOS33 } [get_ports { eth_rx_er }]
#set_property -dict { PACKAGE_PIN A16  IOSTANDARD LVCMOS33 } [get_ports { eth_ref_clk }]
#set_property -dict { PACKAGE_PIN K3   IOSTANDARD LVCMOS33 } [get_ports { eth_mdc }]
#set_property -dict { PACKAGE_PIN H1   IOSTANDARD LVCMOS33 } [get_ports { eth_mdio }]
#create_clock -add -name eth_ref_clk_pin -period 20.000 -waveform {0 10} [get_ports { eth_ref_clk }]  # 50 MHz

## TX control to h-bridge sheet (T-013)
set_property -dict { PACKAGE_PIN M3   IOSTANDARD LVCMOS33 } [get_ports { tx_en }]
set_property -dict { PACKAGE_PIN L3   IOSTANDARD LVCMOS33 } [get_ports { tx_ph }]
set_property -dict { PACKAGE_PIN V8   IOSTANDARD LVCMOS33 } [get_ports { tx_nsleep }]
set_property -dict { PACKAGE_PIN C15  IOSTANDARD LVCMOS33 } [get_ports { tx_nfault }]
set_property -dict { PACKAGE_PIN B15  IOSTANDARD LVCMOS33 } [get_ports { tx_pmode }]

## NOTE for T-020: PDM input timing (tDD 18-40 ns / tDZ 3-16 ns vs pdm_clk_fb both edges)
## belongs in a timing XDC with set_input_delay on both edges; see docs/pdm-capture-contract.md
## and docs/pdm-rx-design.md timing budget (setup 122.2 ns / hold 2.12 ns at 3.072 MHz).

## ----------------------------------------------------------------------------
## MANUAL APPEND (T-020, 2026-08-26) - on-module devices, NOT from the DIP pin
## table in scripts/gen_digital_sheet.py. Regenerating the XDC must keep this
## section. All 30 SRAM pins are dedicated bank-14 Sch=sram-* nets (Cmod A7
## reference manual sec. 3); verified 2026-08-26: zero overlap with the 44 DIP
## pins in orchestration/pinmap.md. Lines below are copied EXACTLY (comment
## leader removed) from the live Digilent Cmod-A7-Master.xdc SRAM section,
## fetched 2026-08-26 (/tmp/cmod-a7-master.xdc).
## On-module 512 KiB SRAM: ISSI IS61WV5128BLL-10BLI, 512Kx8, 8 ns access at 3.3V.
## Board-level set_output_delay/setup-hold budgeting for this bus is host-gated
## with the rest of the Vivado build (ticket T-020 Log).
set_property -dict { PACKAGE_PIN M18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[0]  }]; #IO_L11P_T1_SRCC_14 Sch=sram- a[0]
set_property -dict { PACKAGE_PIN M19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[1]  }]; #IO_L11N_T1_SRCC_14 Sch=sram- a[1]
set_property -dict { PACKAGE_PIN K17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[2]  }]; #IO_L12N_T1_MRCC_14 Sch=sram- a[2]
set_property -dict { PACKAGE_PIN N17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[3]  }]; #IO_L13P_T2_MRCC_14 Sch=sram- a[3]
set_property -dict { PACKAGE_PIN P17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[4]  }]; #IO_L13N_T2_MRCC_14 Sch=sram- a[4]
set_property -dict { PACKAGE_PIN P18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[5]  }]; #IO_L14P_T2_SRCC_14 Sch=sram- a[5]
set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[6]  }]; #IO_L14N_T2_SRCC_14 Sch=sram- a[6]
set_property -dict { PACKAGE_PIN W19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[7]  }]; #IO_L16N_T2_A15_D31_14 Sch=sram- a[7]
set_property -dict { PACKAGE_PIN U19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[8]  }]; #IO_L15P_T2_DQS_RDWR_B_14 Sch=sram- a[8]
set_property -dict { PACKAGE_PIN V19   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[9]  }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=sram- a[9]
set_property -dict { PACKAGE_PIN W18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[10] }]; #IO_L16P_T2_CSI_B_14 Sch=sram- a[10]
set_property -dict { PACKAGE_PIN T17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[11] }]; #IO_L17P_T2_A14_D30_14 Sch=sram- a[11]
set_property -dict { PACKAGE_PIN T18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[12] }]; #IO_L17N_T2_A13_D29_14 Sch=sram- a[12]
set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[13] }]; #IO_L18P_T2_A12_D28_14 Sch=sram- a[13]
set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[14] }]; #IO_L18N_T2_A11_D27_14 Sch=sram- a[14]
set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[15] }]; #IO_L19P_T3_A10_D26_14 Sch=sram- a[15]
set_property -dict { PACKAGE_PIN W16   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[16] }]; #IO_L20P_T3_A08_D24_14 Sch=sram- a[16]
set_property -dict { PACKAGE_PIN W17   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[17] }]; #IO_L20N_T3_A07_D23_14 Sch=sram- a[17]
set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports { MemAdr[18] }]; #IO_L21P_T3_DQS_14 Sch=sram- a[18]
set_property -dict { PACKAGE_PIN W15   IOSTANDARD LVCMOS33 } [get_ports { MemDB[0]   }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=sram-dq[0]
set_property -dict { PACKAGE_PIN W13   IOSTANDARD LVCMOS33 } [get_ports { MemDB[1]   }]; #IO_L22P_T3_A05_D21_14 Sch=sram-dq[1]
set_property -dict { PACKAGE_PIN W14   IOSTANDARD LVCMOS33 } [get_ports { MemDB[2]   }]; #IO_L22N_T3_A04_D20_14 Sch=sram-dq[2]
set_property -dict { PACKAGE_PIN U15   IOSTANDARD LVCMOS33 } [get_ports { MemDB[3]   }]; #IO_L23P_T3_A03_D19_14 Sch=sram-dq[3]
set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { MemDB[4]   }]; #IO_L23N_T3_A02_D18_14 Sch=sram-dq[4]
set_property -dict { PACKAGE_PIN V13   IOSTANDARD LVCMOS33 } [get_ports { MemDB[5]   }]; #IO_L24P_T3_A01_D17_14 Sch=sram-dq[5]
set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports { MemDB[6]   }]; #IO_L24N_T3_A00_D16_14 Sch=sram-dq[6]
set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33 } [get_ports { MemDB[7]   }]; #IO_25_14 Sch=sram-dq[7]
set_property -dict { PACKAGE_PIN P19   IOSTANDARD LVCMOS33 } [get_ports { RamOEn     }]; #IO_L10P_T1_D14_14 Sch=sram-oe
set_property -dict { PACKAGE_PIN R19   IOSTANDARD LVCMOS33 } [get_ports { RamWEn     }]; #IO_L10N_T1_D15_14 Sch=sram-we
set_property -dict { PACKAGE_PIN N19   IOSTANDARD LVCMOS33 } [get_ports { RamCEn     }]; #IO_L9N_T1_DQS_D13_14 Sch=sram-ce

## On-module USB-UART bridge (FT2232HQ) - D012 snapshot drain over the Cmod's
## own USB. uart_rxd_out is the FPGA's TX pin (drives the bridge RXD), J18.
## uart_txd_in (J17) stays unconstrained until a control plane needs RX.
set_property -dict { PACKAGE_PIN J18   IOSTANDARD LVCMOS33 } [get_ports { uart_rxd_out }]; #IO_L7N_T1_D10_14 Sch=uart_rxd_out
