## Sonar v1 - Cmod A7-35T constraints (T-011 baseline for T-020)
## GENERATED by scripts/gen_digital_sheet.py - edit the generator or pinmap, not this file.
##
## PROVENANCE: DIP positions, PACKAGE_PINs and IO names VERIFIED 2026-08-26 against
## the live Digilent Cmod-A7-Master.xdc (orchestrator fetch) + reference manual sec. 8.
## The 2026-08-25 offline transcription had all net<->pkg pairings right but sat rows
## 15-44 on wrong DIP positions (pio15/16 = XADC analog, pio24 = VU, pio25 = GND; no 3V3
## pin exists). Fixed by re-map N->N (1-14), N->N+2 (15-21), N->N+4 (22-44); pkg pins
## unchanged. Reproducible check: python3 scripts/check_pinmap_vs_xdc.py (44/44 assert).
## URL: https://github.com/Digilent/digilent-xdc/blob/master/Cmod-A7-Master.xdc
##
## VCCO: all user banks (14/15/16/34/35) are fixed at 3.3V on the Cmod A7 -> LVCMOS33.

## 12 MHz on-module oscillator
set_property -dict { PACKAGE_PIN L17  IOSTANDARD LVCMOS33 } [get_ports { sysclk }]
create_clock -add -name sys_clk_pin -period 83.333 -waveform {0 41.667} [get_ports { sysclk }]

## On-module LEDs / buttons (debug)
set_property -dict { PACKAGE_PIN A17  IOSTANDARD LVCMOS33 } [get_ports { led[0] }]
set_property -dict { PACKAGE_PIN C16  IOSTANDARD LVCMOS33 } [get_ports { led[1] }]
set_property -dict { PACKAGE_PIN B17  IOSTANDARD LVCMOS33 } [get_ports { led0_b }]
set_property -dict { PACKAGE_PIN B16  IOSTANDARD LVCMOS33 } [get_ports { led0_g }]
set_property -dict { PACKAGE_PIN C17  IOSTANDARD LVCMOS33 } [get_ports { led0_r }]
set_property -dict { PACKAGE_PIN A18  IOSTANDARD LVCMOS33 } [get_ports { btn[0] }]
set_property -dict { PACKAGE_PIN B18  IOSTANDARD LVCMOS33 } [get_ports { btn[1] }]

## PDM microphone interface (T-008 baseline: 12 data lines, paired mics, returned clock)
set_property -dict { PACKAGE_PIN J3   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[0] }]
set_property -dict { PACKAGE_PIN J1   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[1] }]
set_property -dict { PACKAGE_PIN K2   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[2] }]
set_property -dict { PACKAGE_PIN L1   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[3] }]
set_property -dict { PACKAGE_PIN L2   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[4] }]
set_property -dict { PACKAGE_PIN M1   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[5] }]
set_property -dict { PACKAGE_PIN N3   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[6] }]
set_property -dict { PACKAGE_PIN P3   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[7] }]
set_property -dict { PACKAGE_PIN M2   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[8] }]
set_property -dict { PACKAGE_PIN N1   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[9] }]
set_property -dict { PACKAGE_PIN N2   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[10] }]
set_property -dict { PACKAGE_PIN P1   IOSTANDARD LVCMOS33 } [get_ports { pdm_d[11] }]
set_property -dict { PACKAGE_PIN A14  IOSTANDARD LVCMOS33 } [get_ports { pdm_clk_src }]
set_property -dict { PACKAGE_PIN A15  IOSTANDARD LVCMOS33 } [get_ports { pdm_clk_en }]
## Returned clock from CDCLVC1112 Y11 - MUST land on a clock-capable pin (pio40, MRCC_34).
## IDDR sampling must use this returned clock, not a copy of the source net (capture contract).
set_property -dict { PACKAGE_PIN W4   IOSTANDARD LVCMOS33 } [get_ports { pdm_clk_fb }]
create_clock -add -name pdm_clk_fb_pin -period 325.521 -waveform {0 162.760} [get_ports { pdm_clk_fb }]  # 3.072 MHz v1 (parameterize; 208.333 ns for the 4.8 MHz ICS alternate)

## FT232H synchronous FIFO (FT245 sync mode, 60 MHz CLKOUT)
set_property -dict { PACKAGE_PIN R3   IOSTANDARD LVCMOS33 } [get_ports { ft_d[0] }]
set_property -dict { PACKAGE_PIN T3   IOSTANDARD LVCMOS33 } [get_ports { ft_d[1] }]
set_property -dict { PACKAGE_PIN R2   IOSTANDARD LVCMOS33 } [get_ports { ft_d[2] }]
set_property -dict { PACKAGE_PIN T1   IOSTANDARD LVCMOS33 } [get_ports { ft_d[3] }]
set_property -dict { PACKAGE_PIN T2   IOSTANDARD LVCMOS33 } [get_ports { ft_d[4] }]
set_property -dict { PACKAGE_PIN U1   IOSTANDARD LVCMOS33 } [get_ports { ft_d[5] }]
set_property -dict { PACKAGE_PIN W2   IOSTANDARD LVCMOS33 } [get_ports { ft_d[6] }]
set_property -dict { PACKAGE_PIN V2   IOSTANDARD LVCMOS33 } [get_ports { ft_d[7] }]
set_property -dict { PACKAGE_PIN W3   IOSTANDARD LVCMOS33 } [get_ports { ft_rxf_n }]
set_property -dict { PACKAGE_PIN V3   IOSTANDARD LVCMOS33 } [get_ports { ft_txe_n }]
set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports { ft_rd_n }]
set_property -dict { PACKAGE_PIN V4   IOSTANDARD LVCMOS33 } [get_ports { ft_wr_n }]
set_property -dict { PACKAGE_PIN U4   IOSTANDARD LVCMOS33 } [get_ports { ft_oe_n }]
set_property -dict { PACKAGE_PIN U8   IOSTANDARD LVCMOS33 } [get_ports { ft_clkout }]
create_clock -add -name ft_clkout_pin -period 16.667 -waveform {0 8.333} [get_ports { ft_clkout }]  # 60 MHz

## DNP RMII Ethernet provision (LAN8720A + 50 MHz osc; not populated on v1)
## Uncomment when the DNP block is populated.
#set_property -dict { PACKAGE_PIN V5   IOSTANDARD LVCMOS33 } [get_ports { eth_txd[0] }]
#set_property -dict { PACKAGE_PIN U5   IOSTANDARD LVCMOS33 } [get_ports { eth_txd[1] }]
#set_property -dict { PACKAGE_PIN U2   IOSTANDARD LVCMOS33 } [get_ports { eth_tx_en }]
#set_property -dict { PACKAGE_PIN W6   IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[0] }]
#set_property -dict { PACKAGE_PIN U3   IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[1] }]
#set_property -dict { PACKAGE_PIN U7   IOSTANDARD LVCMOS33 } [get_ports { eth_crs_dv }]
#set_property -dict { PACKAGE_PIN W7   IOSTANDARD LVCMOS33 } [get_ports { eth_rx_er }]
#set_property -dict { PACKAGE_PIN A16  IOSTANDARD LVCMOS33 } [get_ports { eth_ref_clk }]
#set_property -dict { PACKAGE_PIN K3   IOSTANDARD LVCMOS33 } [get_ports { eth_mdc }]
#set_property -dict { PACKAGE_PIN H1   IOSTANDARD LVCMOS33 } [get_ports { eth_mdio }]
#create_clock -add -name eth_ref_clk_pin -period 20.000 -waveform {0 10} [get_ports { eth_ref_clk }]  # 50 MHz

## TX control to h-bridge sheet (T-013)
set_property -dict { PACKAGE_PIN M3   IOSTANDARD LVCMOS33 } [get_ports { tx_en }]
set_property -dict { PACKAGE_PIN L3   IOSTANDARD LVCMOS33 } [get_ports { tx_ph }]
set_property -dict { PACKAGE_PIN V8   IOSTANDARD LVCMOS33 } [get_ports { tx_nsleep }]
set_property -dict { PACKAGE_PIN C15  IOSTANDARD LVCMOS33 } [get_ports { tx_nfault }]
set_property -dict { PACKAGE_PIN B15  IOSTANDARD LVCMOS33 } [get_ports { tx_pmode }]

## NOTE for T-020: PDM input timing (tDD 18-40 ns / tDZ 3-16 ns vs pdm_clk_fb both edges)
## belongs in a timing XDC with set_input_delay on both edges; see docs/pdm-capture-contract.md
## and docs/pdm-rx-design.md timing budget (setup 122.2 ns / hold 2.12 ns at 3.072 MHz).
