[workspace]
pcb-version = "0.4"
vendor = ["code.diode.computer/diode/registry/**"]

[board]
name = "power_supply"
path = "power_supply.zen"
description = "Replace with concise board description."

[access]
allow = ["*"]